This package provides functions to convert an Emacs string with text properties
(i.e. faces) into a standalone SVG image, preserving the original colors and
styling.

#+BEGIN_SRC emacs-lisp :results file :file ./assets/the-quick-brown-fox.svg
(propertized-text-to-svg
 (concat (propertize "The" 'face '(:foreground "black"))
         " "
         (propertize "quick" 'face '(:foreground "brown" :weight bold))
         " "
         (propertize "brown" 'face '(:foreground "brown" :slant italic))
         " "
         (propertize "fox" 'face '(:foreground "orange red" :underline t))
         " "
         (propertize "jumps over the" 'face '(:foreground "black"))
         " "
         (propertize "lazy" 'face '(:foreground "grey" :strike-through t))
         " "
         (propertize "dog." 'face '(:foreground "black" :weight heavy))))
#+END_SRC

[[file:./assets/the-quick-brown-fox.svg]]

#+BEGIN_SRC emacs-lisp :results file :file ./assets/normal-bold-italic.svg
(propertized-text-to-svg
 (concat (propertize "Normal " 'face '(:weight normal :slant normal))
         (propertize "Bold " 'face '(:weight bold))
         (propertize "Italic " 'face '(:slant italic))))
#+END_SRC

[[file:./assets/normal-bold-italic.svg]]

#+BEGIN_SRC emacs-lisp :results file :file ./assets/height.svg
(propertized-text-to-svg
 (concat (propertize "Serif 12pt" 'face '(:family "serif" :height 120))
         " "
         (propertize "Monospace 1.2x" 'face '(:family "monospace" :height 1.2))))
#+END_SRC

[[file:./assets/height.svg]]

#+BEGIN_SRC emacs-lisp :results file :file ./assets/decorations.svg
(propertized-text-to-svg
 (concat (propertize "overline" 'face '(:overline t))
         " "
         (propertize "strike-through" 'face '(:strike-through t))
         " "
         (propertize "underline" 'face '(:underline t))))
#+END_SRC

[[file:./assets/decorations.svg]]

* See [[https://github.com/rgkirch/my-emacs-packages][my other emacs packages]]
* License

Copyright (C) 2025 Richie Kirchofer

SPDX-License-Identifier: GPL-3.0-or-later

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
